MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "weights/swin_base_patch4_window12_384.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
DATASETS:
  TRAIN: ("coco_lvis_2017_train",)
  TEST: ("GrabCut",)
SOLVER:
  IMS_PER_BATCH: 1 #16
  BASE_LR: 0.00005 #0.0001
  STEPS: (327778, 355092)
  MAX_ITER: 368750 #368750
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 10000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 512 #1024
  MIN_AREA_FOR_MASK: 400.0
  DISTRACTOR_BG: False
  DISTRACTOR_OBJECTS: False
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_lvis_multi_insts_stuff_mq"
TEST:
  EVAL_PERIOD: 400000
DATALOADER:
  # DISTRACTOR_OBJECTS: False
  # DISTRACTOR_BG: False
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
# ITERATIVE:
#   TRAIN:
#     ACCUMULATE_INTERACTION_LOSS: False
#     MAX_NUM_INTERACTIONS: 10
#     RANDOM_INSTANCES_INTERACTION: False
#     SINGLE_INSTANCE_INTERACTION: False
#     INTERACTION_RESET_PROBABILITY:  0.0
#     BACKPROP_CLASSIFICATION_SCORE: True
#   TEST:
#     INTERACTIVE_EVALAUTION: False
#     MAX_NUM_INTERACTIONS: 20
#     IOU_THRESHOLD: 0.85
# VERSION: 2
