_BASE_: swin-base.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "weights/swin_large_patch4_window12_384_22k.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    REFINE_MASK_FEATURES: True
ITERATIVE:
  TRAIN:
    #PER_OBJ_SAMPLING: True
    USE_POS_COORDS: True
    USE_TIME_COORDS: True
    USE_POINT_FEATURES: True
    USE_COORDS_ON_POINT_MASKS: False
    UNIQUE_TIMESTAMP: True
    USE_ARGMAX: True
    USE_STATIC_BG_QUERIES: True
    NUM_STATIC_BG_QUERIES: 9
    CONCAT_XYT: True
    STUFF_PROB: 0.15
INPUT:
  IMAGE_SIZE: 1024
  MIN_AREA_FOR_MASK: 1000.0
REVERSE_CROSS_ATTN:
  USE_REVERSE_CROSS_ATTN: True
  USE_MLP_REV_ATTN: True
  NUM_LAYERS: 5
  SCALE_FACTOR: 1.0
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0001 #5e-4
  STEPS: (327778, 355092)
  MAX_ITER: 368750
DATASETS:
  TRAIN: ("coco_lvis_2017_train",)
INPUT:
  DATASET_MAPPER_NAME: "coco_lvis_multi_insts_stuff_coords_mq"
# SEED: 2091831170
VERSION: 2
