_BASE_: ../resnet/multi_queries_stufff_clicks_R50_bs32_ep50.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  WEIGHTS: "weights/swin_large_patch4_window12_384_22k.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
SOLVER:
  IMS_PER_BATCH: 32 #16
  BASE_LR: 0.0001
  STEPS: (327778, 355092) #(163889, 177546)
  MAX_ITER: 368750 #184375 
