MODEL:
  META_ARCHITECTURE: "DynamiteModel"
  SEM_SEG_HEAD:
    NAME: "DynamiteHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 80
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    # TRANSFORMER_DECODER_NAME: "InteractiveTransformerDecoder"
    INTERACTIVE_TRANSFORMER_NAME: "DynamiteInteractiveTransformer"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    # QUERY_INITIALIZER: "multi_scale" # OR single_scale
    DEEP_SUPERVISION: True
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    # ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    ENC_LAYERS: 10  # 9 encoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    DECODER:
      USE_DECODER: True
      DEC_LAYERS: 5
      DEC_SCALE_FACTOR: 1.0
SOLVER:
  IMS_PER_BATCH: 16 #16
  BASE_LR: 0.0001
  STEPS: (327778, 355092)
  MAX_ITER: 368750 #368750
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 10000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
DATASETS:
  TRAIN: ("coco_lvis_2017_train",)
  TEST: ("GrabCut",)
INPUT:
  IMAGE_SIZE: 1024
  MIN_AREA_FOR_MASK: 400.0
  DISTRACTOR_BG: False
  DISTRACTOR_OBJECTS: False
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_lvis"
TEST:
  EVAL_PERIOD: 400000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
ITERATIVE:
  TRAIN:
    # CLASS_AGNOSTIC: True
    NUM_STATIC_BG_QUERIES: 9
    MAX_NUM_INTERACTIONS: 3
  TEST:
    INTERACTIVE_EVALAUTION: True
    # EVAL_STRATEGY: "random"
    MAX_NUM_INTERACTIONS: 20
    IOU_THRESHOLD: 0.85

VERSION: 2

