_BASE_: hrnet-base.yaml
MODEL:
  BACKBONE:
    NAME: "HigherResolutionNet"
    FREEZE_AT: 0
  WEIGHTS: "weights/hrnetv2_w32_imagenet_pretrained_trans.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    REFINE_MASK_FEATURES: True
ITERATIVE:
  TRAIN:
    # PER_OBJ_SAMPLING: True
    USE_POS_COORDS: True
    USE_TIME_COORDS: True
    USE_POINT_FEATURES: True
    USE_COORDS_ON_POINT_MASKS: False
    UNIQUE_TIMESTAMP: True
    USE_ARGMAX: True
    USE_STATIC_BG_QUERIES: True
    NUM_STATIC_BG_QUERIES: 9
    CONCAT_XYT: True
    STUFF_PROB: 0.15
INPUT:
  IMAGE_SIZE: 1024
  MIN_AREA_FOR_MASK: 1000.0
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (327778, 355092)
  MAX_ITER: 368750
DATASETS:
  TRAIN: ("coco_lvis_2017_train",)
INPUT:
  DATASET_MAPPER_NAME: "coco_lvis_multi_insts_stuff_coords_mq"
VERSION: 2
