_BASE_: ../swin-base.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  WEIGHTS: "weights/swin_tiny_patch4_window7_224.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    REFINE_MASK_FEATURES: True
ITERATIVE:
  TRAIN:
    #PER_OBJ_SAMPLING: True
    USE_POS_COORDS: True
    USE_TIME_COORDS: True
    USE_POINT_FEATURES: True
    USE_COORDS_ON_POINT_MASKS: False
    UNIQUE_TIMESTAMP: True
    USE_ARGMAX: True
    USE_STATIC_BG_QUERIES: True
    NUM_STATIC_BG_QUERIES: 9
    CONCAT_XYT: True
    STUFF_PROB: 0.15
INPUT:
  IMAGE_SIZE: 1024
  MIN_AREA_FOR_MASK: 1000.0
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001 #5e-4
  STEPS: (327778, 355092) #(41000, 44400) #(81945, 88773) #(163889, 177546) 
  MAX_ITER: 368750 #46500 #92188 #184375
DATASETS:
  TRAIN: ("coco_lvis_2017_train",)
INPUT:
  DATASET_MAPPER_NAME: "coco_lvis_multi_insts_stuff_coords_mq"
VERSION: 2
