MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "weights/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("coco_lvis_2017_train",)
  TEST: ("GrabCut",)
SOLVER:
  IMS_PER_BATCH: 16 #16
  BASE_LR: 0.0001
  STEPS: (327778, 355092)
  MAX_ITER: 368750 #368750
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 30000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 512 #1024
  MIN_AREA_FOR_MASK: 400.0
  DISTRACTOR_BG: False
  DISTRACTOR_OBJECTS: False
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_lvis_multi_insts_stuff_mq"
TEST:
  EVAL_PERIOD: 400000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
ITERATIVE:
  TRAIN:
    USE_POINTS: True
    USE_SCRIBBLES: False
    MIXED_TRAINING: False
    PROBABILITY_POINTS: 0.5
    CLASS_AGNOSTIC: True
    CONCAT_COORD_MASK_FEATURES: False
    USE_CNN_BLOCK: False
    CONCAT_COORD_IMAGE_FEATURES: False
    RANDOM_BG_QUERIES: True
    NUM_STATIC_BG_QUERIES: 9
    USE_POS_COORDS: True
    ACCUMULATE_INTERACTION_LOSS: True
    MAX_NUM_INTERACTIONS: 3
    RANDOM_INSTANCES_INTERACTION: False
    SINGLE_INSTANCE_INTERACTION: False
    INTERACTION_RESET_PROBABILITY:  0.0
    BACKPROP_CLASSIFICATION_SCORE: True
  TEST:
    INTERACTIVE_EVALAUTION: True
    MAX_NUM_INTERACTIONS: 20
    IOU_THRESHOLD: 0.85
REVERSE_CROSS_ATTN:
  USE_REVERSE_CROSS_ATTN: True
  NUM_LAYERS: 5
  SCALE_FACTOR: 1.0
