_BASE_: resnet-base.yaml
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "weights/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  SEM_SEG_HEAD:
    REFINE_MASK_FEATURES: True
ITERATIVE:
  TRAIN:
    POSITIONAL_EMBED: "spatio_temporal" #[ "temporal", "spatial", "spatio_temporal", None]
    USE_STATIC_BG_QUERIES: True
    NUM_STATIC_BG_QUERIES: 9
INPUT:
  IMAGE_SIZE: 1024
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0001 #5e-4
  STEPS: (163889, 177546) #(327778, 355092)
  MAX_ITER: 184375
DATASETS:
  TRAIN: ("coco_lvis_2017_train",)
INPUT:
  DATASET_MAPPER_NAME: "coco_lvis"
SEED: 2091831170
VERSION: 2
