_BASE_: resnet-base.yaml
MODEL:
  SEM_SEG_HEAD:
    REFINE_MASK_FEATURES: True
ITERATIVE:
  TRAIN:
    #PER_OBJ_SAMPLING: True
    USE_POS_COORDS: True
    USE_TIME_COORDS: True
    USE_POINT_FEATURES: True
    USE_COORDS_ON_POINT_MASKS: False
    UNIQUE_TIMESTAMP: True
    USE_ARGMAX: True
INPUT:
  IMAGE_SIZE: 1024
SOLVER:
  IMS_PER_BATCH: 128
  BASE_LR: 0.0005 #5e-4
  STEPS: (41000, 44400) #(81945, 88773) #(163889, 177546) #(327778, 355092)
  MAX_ITER: 46500 #92188 #184375 #368750
DATASETS:
  TRAIN: ("coco_lvis_2017_train",)
INPUT:
  DATASET_MAPPER_NAME: "coco_lvis_multi_insts_stuff_coords_mq"
VERSION: 2
